const privacyContact = "musecards67@gmail.com";
const sections = [
    ["data-we-handle", "Information the service handles"],
    ["device-storage", "Saved collection and settings"],
    ["sharing", "Sharing and external links"],
    ["use-and-disclosure", "How information is used"],
    ["retention", "Retention and deletion"],
    ["security", "Security"],
    ["contact", "Contact"],
    ["changes", "Changes to this policy"],
];
export default function PrivacyPolicyPage() {
    return (<div className="site-shell privacy-page">
      <a className="skip-link" href="#policy-content">Skip to privacy policy</a>
      <header className="site-header privacy-header">
        <a className="wordmark" href="/" aria-label="MuseBooks home">MuseBooks</a>
        <nav className="main-nav" aria-label="Main navigation">
          <a href="/">Back to catalog</a>
        </nav>
      </header>

      <main id="policy-content">
        <section className="privacy-intro" aria-labelledby="policy-title">
          <h1 id="policy-title">Privacy Policy</h1>
          <p>This policy explains how MuseBooks handles information when you use the MuseBooks website and Android app.</p>
          <p className="privacy-updated">Last updated October 7, 2026</p>
        </section>

        <div className="privacy-layout">
          <aside className="privacy-contents" aria-label="Policy contents">
            <h2>Contents</h2>
            <nav>
              {sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}
            </nav>
          </aside>

          <article className="privacy-copy">
            <section id="data-we-handle" className="privacy-section">
              <h2>Information the service handles</h2>
              <p>When you browse the catalog, your browser or app requests catalog and origin information from the MuseBooks API and cover images from our image host. Those requests necessarily expose network details such as your IP address, the requested page or resource, and browser or app information to the systems delivering the response. Hosting and delivery providers may process limited technical logs to operate, secure, and troubleshoot the service.</p>
              <p>The current website and Android app do not provide account sign-up or login. They do not send your saved collection or appearance setting to the MuseBooks API. The app does not include advertising or analytics SDKs.</p>
            </section>

            <section id="device-storage" className="privacy-section">
              <h2>Saved collection and settings</h2>
              <p>Your saved book list and light or dark appearance setting are stored in browser storage on the device you use. They stay on that device and are not synced to a MuseBooks account or uploaded to our catalog API.</p>
            </section>

            <section id="sharing" className="privacy-section">
              <h2>Sharing and external links</h2>
              <p>If you choose to share a book, MuseBooks passes that book’s title and link to your device’s share interface. The app you select receives the information you choose to share and handles it under its own privacy policy.</p>
              <p>Catalog source links open external retailer or publisher websites. Those sites are operated by others and have their own privacy practices; review their policies before sharing information with them.</p>
            </section>

            <section id="use-and-disclosure" className="privacy-section">
              <h2>How information is used</h2>
              <p>MuseBooks uses catalog requests to return books, editions, origins, listings, and cover images. Limited technical request information may be used to keep the service reliable and secure. MuseBooks does not sell personal information or use it for targeted advertising.</p>
            </section>

            <section id="retention" className="privacy-section">
              <h2>Retention and deletion</h2>
              <p>Your saved books and appearance setting remain in local browser or app storage until you remove them, clear that storage, or remove the app. MuseBooks does not keep server-side copies of those preferences. Technical logs generated by hosting or delivery providers follow their operational retention practices and are kept only as needed for service operation, security, troubleshooting, or legal obligations.</p>
              <p>For a privacy question or a request about information associated with your use of MuseBooks, contact us at <a href={`mailto:${privacyContact}`}>{privacyContact}</a>.</p>
            </section>

            <section id="security" className="privacy-section">
              <h2>Security</h2>
              <p>The Android app is configured to connect to the production MuseBooks API over HTTPS. We use reasonable safeguards for the service, but no method of transmission or storage can be guaranteed to be completely secure.</p>
            </section>

            <section id="contact" className="privacy-section">
              <h2>Contact</h2>
              <p>For privacy questions or data requests, email <a href={`mailto:${privacyContact}`}>{privacyContact}</a>. Please identify MuseBooks in your message so we can route your request.</p>
            </section>

            <section id="changes" className="privacy-section">
              <h2>Changes to this policy</h2>
              <p>We may update this policy when the service or its data practices change. The date at the top of this page shows when it was most recently revised.</p>
            </section>
          </article>
        </div>
      </main>

      <footer className="site-footer">
        <span>MuseBooks</span>
        <a href="/">Back to catalog</a>
        <a href={`mailto:${privacyContact}`}>Privacy contact</a>
        <span>Updated October 7, 2026</span>
      </footer>
    </div>);
}
