package database

import (
	"musebooks/model"

	"gorm.io/gorm"
)

func SeedCatalog(db *gorm.DB) error {
	origins := []model.Origin{
		{Code: "JP", Name: "Japan", NativeName: "日本", SortOrder: 1},
		{Code: "TW", Name: "Taiwan", NativeName: "台灣", SortOrder: 2},
		{Code: "CN", Name: "China", NativeName: "中国", SortOrder: 3},
		{Code: "MY", Name: "Malaysia", NativeName: "Malaysia", SortOrder: 4},
	}
	for _, origin := range origins {
		if err := db.Where("code = ?", origin.Code).FirstOrCreate(&origin).Error; err != nil {
			return err
		}
	}

	sources := []model.Source{
		{ID: "ebay", Name: "eBay", Region: "global", Locale: "en-US", Timezone: "UTC", Kind: "marketplace", Adapter: "ebay_browser", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://www.ebay.com", AllowedHosts: "www.ebay.com", Capabilities: "catalog_discovery,active_discovery,sold_discovery,listing_detail", AccessStatus: "browser_review", TermsURL: "https://www.ebay.com/help/policies/member-behaviour-policies/user-agreement?id=4259", RatePerMinute: 6, Enabled: true},
		{ID: "yahoo-auctions-jp", Name: "Yahoo! JAPAN Auctions / JDirectItems Auction", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "marketplace", Adapter: "yahoo_auctions_jp", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://auctions.yahoo.co.jp", AllowedHosts: "auctions.yahoo.co.jp", Capabilities: "active_discovery,sold_discovery,listing_detail", AccessStatus: "browser_review", TermsURL: "https://developer.yahoo.co.jp/", RatePerMinute: 6, Enabled: true},
		{ID: "mercari-jp", Name: "Mercari Japan", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "marketplace", Adapter: "mercari_jp", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://jp.mercari.com", AllowedHosts: "jp.mercari.com", Capabilities: "active_discovery,sold_discovery,listing_detail", AccessStatus: "browser_review", TermsURL: "https://static.jp.mercari.com/tos", RatePerMinute: 6, Enabled: true},
		{ID: "rakuma", Name: "Rakuma", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "marketplace", Adapter: "rakuma_jp", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://fril.jp", AllowedHosts: "fril.jp,item.fril.jp", Capabilities: "active_discovery,sold_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "yahoo-furima-jp", Name: "Yahoo! Flea Market", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "marketplace", Adapter: "yahoo_furima_jp", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://paypayfleamarket.yahoo.co.jp", AllowedHosts: "paypayfleamarket.yahoo.co.jp", Capabilities: "active_discovery,sold_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "surugaya", Name: "Suruga-ya", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "bookstore", Adapter: "surugaya_jp", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://www.suruga-ya.jp", AllowedHosts: "www.suruga-ya.jp", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "blocked", RatePerMinute: 6, Enabled: false},
		{ID: "mandarake", Name: "Mandarake", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "marketplace", Adapter: "mandarake_jp", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://order.mandarake.co.jp", AllowedHosts: "order.mandarake.co.jp,www.mandarake.co.jp", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "review", RatePerMinute: 6, Enabled: false},
		{ID: "books-com-tw", Name: "Books.com.tw", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "bookstore", Adapter: "books_com_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.books.com.tw", AllowedHosts: "www.books.com.tw,search.books.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "ruten-tw", Name: "Ruten", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "marketplace", Adapter: "ruten_tw", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://www.ruten.com.tw", AllowedHosts: "www.ruten.com.tw,pub.ruten.com.tw", Capabilities: "active_discovery,sold_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "shopee-tw", Name: "Shopee Taiwan", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "marketplace", Adapter: "shopee_tw", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://shopee.tw", AllowedHosts: "shopee.tw,www.shopee.tw", Capabilities: "active_discovery,listing_detail", AccessStatus: "blocked", RatePerMinute: 6, Enabled: false},
		{ID: "yahoo-tw", Name: "Yahoo!拍賣 Taiwan", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "marketplace", Adapter: "yahoo_tw", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://tw.bid.yahoo.com", AllowedHosts: "tw.bid.yahoo.com", Capabilities: "active_discovery,sold_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 4, Enabled: true},
		{ID: "bookwalker-tw", Name: "BOOK☆WALKER Taiwan", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "bookwalker_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.bookwalker.com.tw", AllowedHosts: "www.bookwalker.com.tw,bookwalker.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "readmoo-tw", Name: "Readmoo", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "readmoo_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://readmoo.com", AllowedHosts: "readmoo.com,www.readmoo.com", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "pubu-tw", Name: "Pubu", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "pubu_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.pubu.com.tw", AllowedHosts: "www.pubu.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "kobo-tw", Name: "Rakuten Kobo Taiwan", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "kobo_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.kobo.com/tw/zh", AllowedHosts: "www.kobo.com", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "hami-tw", Name: "Hami書城", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "hami_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.hamibook.com.tw", AllowedHosts: "www.hamibook.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "google-play-books-tw", Name: "Google Play Books Taiwan", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "google_play_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://play.google.com/store/books", AllowedHosts: "play.google.com", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "momo-books-tw", Name: "momoBOOK", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "momo_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.momoshop.com.tw", AllowedHosts: "www.momoshop.com.tw,m.momoshop.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "pchome-books-tw", Name: "PChome HyRead電子書", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "pchome_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://24h.pchome.com.tw/books", AllowedHosts: "24h.pchome.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "kingstone-books-tw", Name: "金石堂電子書", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "kingstone_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.kingstone.com.tw", AllowedHosts: "www.kingstone.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "taaze-books-tw", Name: "TAAZE讀冊電子書", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "taaze_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://m.taaze.tw", AllowedHosts: "m.taaze.tw,www.taaze.tw", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "sanmin-books-tw", Name: "三民網路書店", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "sanmin_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.sanmin.com.tw", AllowedHosts: "www.sanmin.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "fan520-tw", Name: "Fan520 女神範", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "fan520_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://www.fan520.net", AllowedHosts: "www.fan520.net", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "apple-books-tw", Name: "Apple Books Taiwan", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "apple_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://books.apple.com/tw", AllowedHosts: "books.apple.com", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "review", RatePerMinute: 6, Enabled: false},
		{ID: "apple-books-us", Name: "Apple Books US (Taiwan model editions)", Region: "US", Locale: "en-US", Timezone: "America/Los_Angeles", Kind: "digital_store", Adapter: "apple_books_us", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://books.apple.com/us", AllowedHosts: "books.apple.com", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "hyread-tw", Name: "HyRead ebook", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "hyread_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://ebook.hyread.com.tw", AllowedHosts: "ebook.hyread.com.tw", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "blocked", RatePerMinute: 6, Enabled: false},
		{ID: "yahoo-shopping-books-tw", Name: "Yahoo購物中心電子書", Region: "TW", Locale: "zh-TW", Timezone: "Asia/Taipei", Kind: "digital_store", Adapter: "yahoo_shopping_books_tw", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://tw.buy.yahoo.com", AllowedHosts: "tw.buy.yahoo.com", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "carousell-my", Name: "Carousell Malaysia", Region: "MY", Locale: "en-MY", Timezone: "Asia/Kuala_Lumpur", Kind: "marketplace", Adapter: "carousell_my", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://www.carousell.com.my", AllowedHosts: "www.carousell.com.my", Capabilities: "active_discovery,listing_detail", AccessStatus: "review", RatePerMinute: 6, Enabled: false},
		{ID: "shopee-my", Name: "Shopee Malaysia", Region: "MY", Locale: "en-MY", Timezone: "Asia/Kuala_Lumpur", Kind: "marketplace", Adapter: "shopee_my", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://shopee.com.my", AllowedHosts: "shopee.com.my,www.shopee.com.my", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "lazada-my", Name: "Lazada Malaysia", Region: "MY", Locale: "en-MY", Timezone: "Asia/Kuala_Lumpur", Kind: "marketplace", Adapter: "lazada_my", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://www.lazada.com.my", AllowedHosts: "www.lazada.com.my", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "bookwalker-jp", Name: "BOOK☆WALKER Japan", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "digital_store", Adapter: "bookwalker_jp", DefaultFormat: "digital", AllowedFormats: "digital", AccessMethod: "browser", BaseURL: "https://bookwalker.jp", AllowedHosts: "bookwalker.jp,www.bookwalker.jp", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: false},
		{ID: "rakuten-books-jp", Name: "Rakuten Books", Region: "JP", Locale: "ja-JP", Timezone: "Asia/Tokyo", Kind: "bookstore", Adapter: "rakuten_books_jp", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://books.rakuten.co.jp", AllowedHosts: "books.rakuten.co.jp", Capabilities: "catalog_discovery,active_discovery,listing_detail", AccessStatus: "browser_review", TermsURL: "https://books.rakuten.co.jp/info/copyright/", RatePerMinute: 6, Enabled: false},
		{ID: "jd-cn", Name: "JD.com", Region: "CN", Locale: "zh-CN", Timezone: "Asia/Shanghai", Kind: "marketplace", Adapter: "jd_cn", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://search.jd.com", AllowedHosts: "item.jd.com,search.jd.com,www.jd.com", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: true},
		{ID: "taobao-cn", Name: "Taobao / Tmall", Region: "CN", Locale: "zh-CN", Timezone: "Asia/Shanghai", Kind: "marketplace", Adapter: "taobao_cn", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://s.taobao.com", AllowedHosts: "s.taobao.com,www.taobao.com,item.taobao.com,detail.tmall.com,www.tmall.com", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "browser_review", RatePerMinute: 6, Enabled: false},
		{ID: "xianyu-cn", Name: "Xianyu / Goofish", Region: "CN", Locale: "zh-CN", Timezone: "Asia/Shanghai", Kind: "marketplace", Adapter: "xianyu_cn", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://www.goofish.com", AllowedHosts: "www.goofish.com", Capabilities: "active_discovery,listing_detail", AccessStatus: "review", RatePerMinute: 3, Enabled: false},
		{ID: "dangdang-cn", Name: "Dangdang", Region: "CN", Locale: "zh-CN", Timezone: "Asia/Shanghai", Kind: "bookstore", Adapter: "dangdang_cn", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://search.dangdang.com", AllowedHosts: "search.dangdang.com,product.dangdang.com,www.dangdang.com", Capabilities: "catalog_discovery,listing_detail", AccessStatus: "review", RatePerMinute: 6, Enabled: false},
		{ID: "mudah-my", Name: "Mudah.my", Region: "MY", Locale: "en-MY", Timezone: "Asia/Kuala_Lumpur", Kind: "marketplace", Adapter: "mudah_my", DefaultFormat: "physical", AllowedFormats: "physical", AccessMethod: "browser", BaseURL: "https://www.mudah.my", AllowedHosts: "www.mudah.my,mudah.my", Capabilities: "active_discovery,listing_detail", AccessStatus: "review", RatePerMinute: 3, Enabled: false},
	}
	for _, source := range sources {
		if err := db.Where("id = ?", source.ID).Assign(source).FirstOrCreate(&source).Error; err != nil {
			return err
		}
	}

	return nil
}
